version: '2'
services:
  web:
    image: node:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "33000:3000"
    links:
      - cloudant
    network_mode: bridge
  cloudant:
    image: ibmcom/cloudant-developer:latest
    ports:
      - "30080:80"
    expose:
      - "80"
    volumes:
      - cloudant:/srv
    mem_limit: 256M
    restart: always
    hostname: cloudant
    #privileged: true
    network_mode: bridge
volumes:
  cloudant:
