version: '2'
services:
  db:
    image: dcheese/cloudant-developer
    volumes:
      - cloudant:/srv
    ports:
      - "30080:80"
    privileged: true
  web:
    image: node:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "33000:3000"
    depends_on:
      - db
volumes:
  cloudant:
    external: false
