version: '2'
services:
  cloudant:
    image: ibmcom/cloudant-developer
    volumes:
      - cloudant:/srv
    ports:
      - "30080:80"
    hostname: cloudant
    network_mode: bridge
    privileged: true
  web:
    image: node:latest    
    volumes:
      - ./src/app:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "33000:3000"
    links:
      - cloudant
volumes:
  cloudant:
    external: true
